### PR TITLE
Project coordinates in README are updated, urls and library versions …

### PR DESCRIPTION
**Pull request by solomax**
…are updated

### CODE REVIEW

**Comment by solomax** [comment]
Are you planning to release master branch?
I can see only 1 release and it is very much old :(

**Comment by sannies** [comment]
Yes, I will. I'll put it on one of my todo cards. This week.

**Comment by solomax** [comment]
Thanks a lot!
What is the main development branch?
Is it good idea to propose Apache Tika to switch to 1.9 release?

**Comment by sannies** [comment]
The process of switching from one API version to the other is very slow. In the end I will move to the API that is on the master branch but nevertheless I still got projects using the 1.x branch.  Once I ported those projects I'll retire 1.x

**Comment by solomax** [comment]
We successfully moved red5 to the master
I'll to prepare PR for Tika
The more projects will move, the better :))
Thanks!

**Comment by solomax** [comment]
Hello @sannies any new estimates on new release?

**Pull request merged**
